server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useSSL=false
    username: dfrb45
    password: oM27032002
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE